application: hackernews-feed 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /update/.*
  script: appengine.app
  login: admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?venv
- ^(.*/)?hackernews
